---
kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: s2i-core
  namespace: fedora-php-s2i-builds
spec:
  tags:
    - name: latest
      from:
        kind: DockerImage
        name: 'registry.fedoraproject.org/f32/s2i-core:latest'
---
kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: fedora-php-s2i-base
  namespace: fedora-php-s2i-builds
spec:
  tags:
    - name: '32'
      from:
        kind: DockerImage
        name: 'quay.io/cuppett/fedora-php-s2i-base:32'